export const mockPriests = [
  {
    id: '1',
    name: 'Pandit Rajesh Kumar',
    specialty: 'Vedic Rituals',
    rating: 5,
    reviews: 127,
    location: 'Delhi',
    experience: 15,
    image: '/priest1.jpg',
    price: 500,
    languages: ['Hindi', 'Sanskrit', 'English'],
    services: ['Vedic Rituals', 'Aarti Ceremonies', 'Vedic Chanting'],
    bio: 'Expert in traditional Vedic rituals with 15 years of experience.',
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  },
  {
    id: '2',
    name: 'Pandit Arjun Singh',
    specialty: 'Marriage Ceremonies',
    rating: 4.8,
    reviews: 89,
    location: 'Mumbai',
    experience: 12,
    image: '/priest2.jpg',
    price: 600,
    languages: ['Hindi', 'English', 'Marathi'],
    services: ['Marriage Ceremonies', 'Griha Pravesh', 'Yagna'],
    bio: 'Specializes in wedding ceremonies and auspicious occasions.',
    availability: ['Friday', 'Saturday', 'Sunday'],
  },
  {
    id: '3',
    name: 'Pandit Vikram Sharma',
    specialty: 'Home Poojas',
    rating: 4.9,
    reviews: 156,
    location: 'Bangalore',
    experience: 18,
    image: '/priest3.jpg',
    price: 450,
    languages: ['Hindi', 'Kannada', 'English', 'Tamil'],
    services: ['Home Poojas', 'Satyanarayan Katha', 'Mundan'],
    bio: 'Dedicated priest offering comprehensive home pooja services.',
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  {
    id: '4',
    name: 'Pandit Amit Patel',
    specialty: 'Birth Ceremonies',
    rating: 4.7,
    reviews: 92,
    location: 'Pune',
    experience: 10,
    image: '/priest1.jpg',
    price: 400,
    languages: ['Hindi', 'Gujarati', 'Marathi', 'English'],
    services: ['Birth Ceremonies', 'Mundan', 'Upanayan'],
    bio: 'Experienced in traditional birth and childhood rituals.',
    availability: ['Tuesday', 'Wednesday', 'Thursday', 'Saturday', 'Sunday'],
  },
  {
    id: '5',
    name: 'Pandit Sanjay Mishra',
    specialty: 'Temple Services',
    rating: 4.6,
    reviews: 114,
    location: 'Hyderabad',
    experience: 20,
    image: '/priest2.jpg',
    price: 550,
    languages: ['Hindi', 'Telugu', 'Sanskrit', 'English'],
    services: ['Temple Services', 'Vedic Rituals', 'Yagna'],
    bio: 'Expert priest with extensive temple and ritual experience.',
    availability: ['Monday', 'Wednesday', 'Friday', 'Sunday'],
  },
  {
    id: '6',
    name: 'Pandit Harish Kumar',
    specialty: 'Aarti Ceremonies',
    rating: 4.8,
    reviews: 103,
    location: 'Chennai',
    experience: 14,
    image: '/priest3.jpg',
    price: 380,
    languages: ['Tamil', 'Telugu', 'Hindi', 'English'],
    services: ['Aarti Ceremonies', 'Temple Services', 'Vedic Chanting'],
    bio: 'Specializes in daily aarti and devotional ceremonies.',
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  },
]

export const mockServices = [
  {
    name: 'Griha Pravesh',
    duration: '2-3 hours',
    description: 'Auspicious ceremony for entering a new home',
    category: 'Occasions',
    icon: '🏠',
  },
  {
    name: 'Vivah Samskara',
    duration: '4-6 hours',
    description: 'Traditional wedding ceremony',
    category: 'Ceremonies',
    icon: '💍',
  },
  {
    name: 'Satyanarayan Katha',
    duration: '2 hours',
    description: 'Sacred worship for prosperity and peace',
    category: 'Worship',
    icon: '🙏',
  },
  {
    name: 'Mundan Samskara',
    duration: '1-2 hours',
    description: 'First hair cutting ceremony',
    category: 'Rituals',
    icon: '✨',
  },
  {
    name: 'Upanayan',
    duration: '3-4 hours',
    description: 'Sacred thread ceremony',
    category: 'Rituals',
    icon: '📿',
  },
  {
    name: 'Bhog Preparation',
    duration: '1.5 hours',
    description: 'Blessed food preparation and distribution',
    category: 'Services',
    icon: '🍲',
  },
  {
    name: 'Lakshmi Pooja',
    duration: '1-2 hours',
    description: 'Worship of Goddess Lakshmi for wealth and prosperity',
    category: 'Worship',
    icon: '🪙',
  },
  {
    name: 'Navagraha Shanti',
    duration: '2-3 hours',
    description: 'Rituals to appease the nine celestial planets for harmony',
    category: 'Shanti Pooja',
    icon: '🪐',
  },
  {
    name: 'Rudrabhishek',
    duration: '2 hours',
    description: 'Abhishek of Lord Shiva with sacred chants for blessings',
    category: 'Worship',
    icon: '🕉️',
  },
  {
    name: 'Vastu Shanti',
    duration: '3-4 hours',
    description: 'Ritual to rectify Vastu doshas and invite positive energy',
    category: 'Shanti Pooja',
    icon: '🏡',
  },
  {
    name: 'Ganesh Sthapana',
    duration: '1-2 hours',
    description: 'Invoking Lord Ganesha for auspicious beginnings',
    category: 'Worship',
    icon: '🐘',
  },
  {
    name: 'Kaal Sarp Dosh Pooja',
    duration: '3 hours',
    description: 'Rituals to mitigate Kaal Sarp Dosha effects',
    category: 'Shanti Pooja',
    icon: '🐍',
  },
  {
    name: 'Pitru Tarpan',
    duration: '1-2 hours',
    description: 'Offerings to ancestors for peace and blessings',
    category: 'Rituals',
    icon: '🌼',
  },
  {
    name: 'Annaprashan',
    duration: '1-2 hours',
    description: 'First solid food ceremony for infants',
    category: 'Samskara',
    icon: '🍼',
  },
  {
    name: 'Karva Chauth Katha',
    duration: '1 hour',
    description: 'Traditional Karva Chauth story recitation and puja',
    category: 'Festivals',
    icon: '🌙',
  },
  {
    name: 'Saraswati Pooja',
    duration: '1-2 hours',
    description: 'Worship of Goddess Saraswati for wisdom and arts',
    category: 'Worship',
    icon: '🎼',
  },
  {
    name: 'Durga Pooja (Ghat Sthapana)',
    duration: '2-3 hours',
    description: 'Invocation of Goddess Durga during Navratri',
    category: 'Festivals',
    icon: '🪔',
  },
  {
    name: 'Hanuman Chalisa Path',
    duration: '1 hour',
    description: 'Recital of Hanuman Chalisa for strength and protection',
    category: 'Path',
    icon: '🛡️',
  },
  {
    name: 'Mahamrityunjaya Jaap',
    duration: '2-4 hours',
    description: 'Chanting of the Mahamrityunjaya Mantra for health and longevity',
    category: 'Jaap',
    icon: '🕯️',
  },
  {
    name: 'Chandi Path',
    duration: '3-5 hours',
    description: 'Recital of Durga Saptashati for victory over obstacles',
    category: 'Path',
    icon: '📜',
  },
  {
    name: 'Bhumi Pujan',
    duration: '1-2 hours',
    description: 'Groundbreaking ceremony before construction',
    category: 'Occasions',
    icon: '🏗️',
  },
  {
    name: 'Naamkaran',
    duration: '1-2 hours',
    description: 'Naming ceremony for newborns',
    category: 'Samskara',
    icon: '👶',
  },
  {
    name: 'Mangal Dosh Nivaran',
    duration: '2-3 hours',
    description: 'Remedial puja for Mangal (Mars) dosha',
    category: 'Shanti Pooja',
    icon: '🔴',
  },
  {
    name: 'Tulsi Vivah',
    duration: '1-2 hours',
    description: 'Ceremonial marriage of Tulsi to Lord Vishnu',
    category: 'Festivals',
    icon: '🌿',
  },
  {
    name: 'Sankashti Chaturthi Pooja',
    duration: '1-2 hours',
    description: 'Monthly Ganesha puja for obstacle removal',
    category: 'Festivals',
    icon: '🙏',
  },
  {
    name: 'Diwali Lakshmi-Ganesha Pooja',
    duration: '1-2 hours',
    description: 'Special Diwali worship for prosperity and auspiciousness',
    category: 'Festivals',
    icon: '🎆',
  },
]

export const mockUsers = [
  {
    id: '1',
    name: 'Priya Sharma',
    email: 'priya@email.com',
    phone: '+91-98765-43210',
    bookings: 8,
    totalSpent: 4500,
    joined: '2025-01-15',
  },
  {
    id: '2',
    name: 'Rajesh Kumar',
    email: 'rajesh@email.com',
    phone: '+91-87654-32109',
    bookings: 5,
    totalSpent: 3000,
    joined: '2025-02-20',
  },
  {
    id: '3',
    name: 'Anjali Desai',
    email: 'anjali@email.com',
    phone: '+91-76543-21098',
    bookings: 12,
    totalSpent: 7200,
    joined: '2025-03-10',
  },
]

export const mockBookings = [
  {
    id: 'BK001',
    priestId: '1',
    priestName: 'Pandit Rajesh Kumar',
    userId: 'USER1',
    userName: 'Priya Sharma',
    service: 'Vedic Rituals',
    date: '2025-11-25',
    time: '10:00 AM',
    status: 'upcoming' as const,
    amount: 500,
    location: 'Home, Sector 5, Delhi',
    createdAt: '2025-11-16',
    notes: 'Family gathering, 20 people expected',
  },
  {
    id: 'BK002',
    priestId: '2',
    priestName: 'Pandit Arjun Singh',
    userId: 'USER2',
    userName: 'Rajesh Kumar',
    service: 'Griha Pravesh',
    date: '2025-11-30',
    time: '2:00 PM',
    status: 'upcoming' as const,
    amount: 600,
    location: 'Flat 302, Bandra, Mumbai',
    createdAt: '2025-11-15',
    notes: 'New apartment blessing ceremony',
  },
  {
    id: 'BK003',
    priestId: '3',
    priestName: 'Pandit Vikram Sharma',
    userId: 'USER1',
    userName: 'Priya Sharma',
    service: 'Satyanarayan Katha',
    date: '2025-11-22',
    time: '4:00 PM',
    status: 'completed' as const,
    amount: 450,
    location: 'Community Center, Bangalore',
    createdAt: '2025-11-10',
    rating: 5,
    review: 'Excellent service, very knowledgeable and punctual.',
  },
  {
    id: 'BK004',
    priestId: '1',
    priestName: 'Pandit Rajesh Kumar',
    userId: 'USER3',
    userName: 'Anjali Desai',
    service: 'Aarti Ceremonies',
    date: '2025-12-05',
    time: '6:00 AM',
    status: 'pending' as const,
    amount: 400,
    location: 'Private residence, Delhi',
    createdAt: '2025-11-16',
    notes: 'Morning aarti ceremony',
  },
]

export const mockNotifications = [
  {
    id: 'N001',
    type: 'booking_confirmation' as const,
    title: 'Booking Confirmed!',
    message: 'Your booking with Pandit Rajesh Kumar is confirmed for Nov 25, 10:00 AM',
    timestamp: new Date(Date.now() - 2 * 60 * 1000),
    read: false,
  },
  {
    id: 'N002',
    type: 'booking_reminder' as const,
    title: 'Upcoming Booking',
    message: 'Your pooja with Pandit Vikram Sharma is in 2 days',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    read: false,
  },
  {
    id: 'N003',
    type: 'rating_request' as const,
    title: 'Rate Your Experience',
    message: 'How was your experience with Pandit Vikram Sharma?',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    read: true,
  },
  {
    id: 'N004',
    type: 'priest_update' as const,
    title: 'Priest Available',
    message: 'Pandit Arjun Singh is now available for bookings',
    timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000),
    read: true,
  },
]
